destination:    ./_site
lsi:            false
pygments:       true
markdown:       maruku
permalink:      pretty
extensions:     true
exclude:        ['Rakefile', 'README.markdown', 'TODO.markdown', '_drafts', 'projects']